### PR TITLE
Update from Lineage Os 16

### PR DESCRIPTION
**Pull request by pintaf**

### CODE REVIEW

**Comment by pintaf** [comment]
Hello @pdsouza signoff verification failed, I could sign them off with ```git rebase HEAD~26 --signoff```, but it doesn't make so much sense since I'm not the author of these.
And I actually tried running this command, it create a conflict...

Let me know how to proceed if you absolutely need these signed off

**Comment by pdsouza** [comment]
> Let me know how to proceed if you absolutely need these signed off

Nope, these are fine since they are just commits from upstream LOS.

If you would like to sign them off next time to avoid the DCO check failure, please try using `git merge --signoff` when you merge in upstream LOS16. Rebasing after a merge commit can mess stuff up.

**Review by pdsouza — APPROVED** [review]
LGTM, thanks!

**Comment by pintaf** [comment]
Thanks for the ```git merge --signoff``` tip.
I tried setting git to always signof what I do, but it seems it's not working sinse I always have to amend my commits to sign them off.

I could also add --signoff to my commit command I guess. but I always forget hahaha

**Comment by pdsouza** [comment]
Yeah, it can be annoying if you forget. Have you tried setting `git-config` with [`format.signOff`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-formatsignOff)? It is annoying though because typically you would set this config per repo, but due to AOSP there are so many different repos. If you set the config optiona at the global level then it signs off all your repos, even your local projects which is unnecessary. Sigh...

**Comment by utzcoz** [comment]
I encounter a build error:

```
Error: ~/maruos/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes.jar contains class file com/nvidia/NvAppProfileService.class, which is not in the whitelist
```

**Comment by pdsouza** [comment]
> I encounter a build error:
> 
> ```
> Error: ~/maruos/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes.jar contains class file com/nvidia/NvAppProfileService.class, which is not in the whitelist
> ```

I am running a `repo sync` right now to check.

**Comment by pdsouza** [comment]
@utzcoz Looks like we may need [this](https://github.com/LineageOS/android_build/commit/141e652e2ea6ac4c808b12d4ce20733884d9c50f) patch to our `android_build` repo to whitelist `com/nvidia/NvAppProfileService.class`. Maybe @pintaf missed merging that one (it is easy to forget).

**Comment by pdsouza** [comment]
> @utzcoz Looks like we may need [this](https://github.com/LineageOS/android_build/commit/141e652e2ea6ac4c808b12d4ce20733884d9c50f) patch to our `android_build` repo to whitelist `com/nvidia/NvAppProfileService.class`. Maybe @pintaf missed merging that one (it is easy to forget).

I will merge any updates from LOS16 into `android_build` tonight and run another build to verify everything is OK.

**Comment by pintaf** [comment]
Hi. Just finished to build to confirm I get similar error, and I did.
It's most probably this missing commit that causes the problem.
Sorry for missing that. if @pdsouza can't do it tonight, I will do it tomorrow.

**Comment by pdsouza** [comment]
> Hi. Just finished to build to confirm I get similar error, and I did.

Thanks for confirming!

> It's most probably this missing commit that causes the problem.
> Sorry for missing that. if @pdsouza can't do it tonight, I will do it tomorrow.

I confirm that merging in the latest LOS patches into `android_build` fixes the build error. Merged in https://github.com/maruos/android_platform_build/commit/483b773daa129c0e1d8aec8e940651cc58a627cb.

@utzcoz - You should be able to build without errors now.

**Comment by pintaf** [comment]
Yes, it builds without errors !

**Comment by utzcoz** [comment]
Works fine for me too.

**Comment by pdsouza** [comment]
OK, great, thanks for confirming.

**Pull request merged**
